server:
  port: 8080
  servlet:
    context_path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/club-management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    tomcat:
      max-wait: 10000
      max-active: 10
      initial-size: 2
      min-idle: 1
      max-idle: 3
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
